// ui/src/features/user-management/components/UsersTable.tsx
import { Pencil, Trash2, KeyRound, ShieldCheck, Users as UsersIcon, CheckCircle2, XCircle } from 'lucide-react';
import { Tooltip } from '../../../components/Tooltip';
import type { KeycloakUser } from '../types';

interface Props {
  users: KeycloakUser[];
  loading: boolean;
  canManage: boolean;
  onEdit: (user: KeycloakUser) => void;
  onDelete: (user: KeycloakUser) => void;
  onResetPassword: (user: KeycloakUser) => void;
  onManageRoles: (user: KeycloakUser) => void;
}

export const UsersTable = ({
  users,
  loading,
  canManage,
  onEdit,
  onDelete,
  onResetPassword,
  onManageRoles,
}: Props) => {
  if (loading && users.length === 0) {
    return <div className="py-16 text-center text-slate-400 text-sm">Loading…</div>;
  }

  if (users.length === 0) {
    return (
      <div className="py-16 text-center">
        <UsersIcon className="w-10 h-10 text-slate-300 mx-auto mb-3" />
        <p className="text-slate-500 font-medium">No users found</p>
        <p className="text-sm text-slate-400 mt-1">Try adjusting your search or add a new user.</p>
      </div>
    );
  }

  return (
    <>
      <div>
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-slate-50 border-b border-slate-200">
              <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Username</th>
              <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Name</th>
              <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Email</th>
              <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Status</th>
              <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Roles</th>
              {canManage && <th className="text-right px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Actions</th>}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {users.map(u => (
              <tr key={u.id} className="hover:bg-slate-50 transition-colors">
                <td className="px-4 py-3.5 font-medium text-slate-900">{u.username}</td>
                <td className="px-4 py-3.5 text-slate-700">
                  {[u.firstName, u.lastName].filter(Boolean).join(' ') || <span className="text-slate-400">—</span>}
                </td>
                <td className="px-4 py-3.5 text-slate-700">{u.email ?? <span className="text-slate-400">—</span>}</td>
                <td className="px-4 py-3.5">
                  {u.enabled ? (
                    <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded">
                      <CheckCircle2 className="w-3 h-3" /> Enabled
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 text-xs font-medium text-slate-600 bg-slate-100 px-2 py-0.5 rounded">
                      <XCircle className="w-3 h-3" /> Disabled
                    </span>
                  )}
                </td>
                <td className="px-4 py-3.5">
                  <div className="flex flex-wrap gap-1">
                    {u.roles.length === 0
                      ? <span className="text-slate-400 text-xs">none</span>
                      : u.roles.map(r => (
                        <span
                          key={r}
                          className={[
                            'text-[11px] px-2 py-0.5 rounded font-medium',
                            r === 'admin' ? 'bg-indigo-50 text-indigo-700' : 'bg-slate-100 text-slate-600',
                          ].join(' ')}
                        >
                          {r}
                        </span>
                      ))}
                  </div>
                </td>
                {canManage && (
                  <td className="px-4 py-3.5">
                    <div className="flex items-center justify-end gap-1">
                      <Tooltip label="Edit profile">
                        <button
                          onClick={() => onEdit(u)}
                          className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer"
                        >
                          <Pencil className="w-4 h-4" />
                        </button>
                      </Tooltip>
                      <Tooltip label="Manage roles">
                        <button
                          onClick={() => onManageRoles(u)}
                          className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer"
                        >
                          <ShieldCheck className="w-4 h-4" />
                        </button>
                      </Tooltip>
                      <Tooltip label="Reset password">
                        <button
                          onClick={() => onResetPassword(u)}
                          className="p-1.5 text-slate-400 hover:text-amber-600 hover:bg-amber-50 rounded-lg transition-colors cursor-pointer"
                        >
                          <KeyRound className="w-4 h-4" />
                        </button>
                      </Tooltip>
                      <Tooltip label="Delete user">
                        <button
                          onClick={() => onDelete(u)}
                          className="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors cursor-pointer"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </Tooltip>
                    </div>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {loading && (
        <div className="border-t border-slate-100 py-3 text-center text-slate-400 text-xs">Refreshing…</div>
      )}
    </>
  );
};

// ui/src/app/features/users/components/users-table/users-table.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import {
  CheckCircle2,
  KeyRound,
  LucideAngularModule,
  Pencil,
  ShieldCheck,
  Trash2,
  Users as UsersIcon,
  XCircle,
} from 'lucide-angular';
import { TableModule } from 'primeng/table';
import { TooltipModule } from 'primeng/tooltip';
import { KeycloakUser } from '../../models/user.model';

/** Users list on a sortable PrimeNG p-table with status + role chips. */
@Component({
  selector: 'app-users-table',
  imports: [TableModule, TooltipModule, LucideAngularModule],
  templateUrl: './users-table.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UsersTableComponent {
  readonly users = input.required<KeycloakUser[]>();
  readonly loading = input(false);
  readonly canManage = input(false);
  readonly edit = output<KeycloakUser>();
  readonly remove = output<KeycloakUser>();
  readonly resetPassword = output<KeycloakUser>();
  readonly manageRoles = output<KeycloakUser>();

  protected readonly UsersIcon = UsersIcon;
  protected readonly CheckCircle2 = CheckCircle2;
  protected readonly XCircle = XCircle;
  protected readonly Pencil = Pencil;
  protected readonly ShieldCheck = ShieldCheck;
  protected readonly KeyRound = KeyRound;
  protected readonly Trash2 = Trash2;

  protected fullName(u: KeycloakUser): string {
    return [u.firstName, u.lastName].filter(Boolean).join(' ');
  }
}

@if (loading() && users().length === 0) {
  <div class="py-16 text-center text-sm opacity-50">Loading…</div>
} @else if (users().length === 0) {
  <div class="py-16 text-center">
    <lucide-icon [img]="UsersIcon" class="mx-auto mb-3 h-10 w-10 opacity-30" />
    <p class="font-medium opacity-70">No users found</p>
    <p class="mt-1 text-sm opacity-50">Try adjusting your search or add a new user.</p>
  </div>
} @else {
  <p-table [value]="users()" styleClass="w-full" [tableStyle]="{ 'min-width': '56rem' }">
    <ng-template pTemplate="header">
      <tr>
        <th pSortableColumn="username">Username <p-sortIcon field="username" /></th>
        <th>Name</th>
        <th pSortableColumn="email">Email <p-sortIcon field="email" /></th>
        <th pSortableColumn="enabled">Status <p-sortIcon field="enabled" /></th>
        <th>Roles</th>
        @if (canManage()) {
          <th class="text-right">Actions</th>
        }
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-u>
      <tr>
        <td class="font-medium">{{ u.username }}</td>
        <td>{{ fullName(u) || '-' }}</td>
        <td>{{ u.email || '-' }}</td>
        <td>
          @if (u.enabled) {
            <span
              class="inline-flex items-center gap-1 rounded bg-emerald-50 px-2 py-0.5 text-xs font-medium text-emerald-700"
            >
              <lucide-icon [img]="CheckCircle2" class="h-3 w-3" /> Enabled
            </span>
          } @else {
            <span
              class="inline-flex items-center gap-1 rounded bg-black/5 px-2 py-0.5 text-xs font-medium opacity-70"
            >
              <lucide-icon [img]="XCircle" class="h-3 w-3" /> Disabled
            </span>
          }
        </td>
        <td>
          <div class="flex flex-wrap gap-1 py-1">
            @for (r of u.roles; track r) {
              <span
                class="rounded px-2 py-0.5 text-[11px] font-medium"
                [class]="r === 'admin' ? 'bg-indigo-50 text-indigo-700' : 'bg-black/5 opacity-70'"
              >
                {{ r }}
              </span>
            } @empty {
              <span class="text-xs opacity-40">none</span>
            }
          </div>
        </td>
        @if (canManage()) {
          <td class="text-right whitespace-nowrap">
            <button
              type="button"
              pTooltip="Edit profile"
              aria-label="Edit profile"
              class="rounded-lg p-2 opacity-70 hover:opacity-100"
              (click)="edit.emit(u)"
            >
              <lucide-icon [img]="Pencil" class="h-4 w-4" />
            </button>
            <button
              type="button"
              pTooltip="Manage roles"
              aria-label="Manage roles"
              class="rounded-lg p-2 opacity-70 hover:opacity-100"
              (click)="manageRoles.emit(u)"
            >
              <lucide-icon [img]="ShieldCheck" class="h-4 w-4" />
            </button>
            <button
              type="button"
              pTooltip="Reset password"
              aria-label="Reset password"
              class="rounded-lg p-2 opacity-70 hover:opacity-100"
              (click)="resetPassword.emit(u)"
            >
              <lucide-icon [img]="KeyRound" class="h-4 w-4" />
            </button>
            <button
              type="button"
              pTooltip="Delete user"
              aria-label="Delete user"
              class="rounded-lg p-2 opacity-70 hover:opacity-100"
              (click)="remove.emit(u)"
            >
              <lucide-icon [img]="Trash2" class="h-4 w-4" />
            </button>
          </td>
        }
      </tr>
    </ng-template>
  </p-table>

  @if (loading()) {
    <div
      class="border-t py-3 text-center text-xs opacity-50"
      style="border-color: var(--p-content-border-color)"
    >
      Refreshing…
    </div>
  }
}
