// ui/src/app/features/inventory/components/inventory-table/inventory-table.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { Boxes, LucideAngularModule, Plus, Sliders } from 'lucide-angular';
import { TableModule } from 'primeng/table';
import { TooltipModule } from 'primeng/tooltip';
import { InventoryItem } from '../../models/inventory.model';

/** Inventory list on a sortable PrimeNG p-table with a stock-level badge. */
@Component({
  selector: 'app-inventory-table',
  imports: [TableModule, TooltipModule, LucideAngularModule],
  templateUrl: './inventory-table.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InventoryTableComponent {
  readonly items = input.required<InventoryItem[]>();
  readonly loading = input(false);
  readonly canManage = input(false);
  readonly receive = output<InventoryItem>();
  readonly adjust = output<InventoryItem>();

  protected readonly Boxes = Boxes;
  protected readonly Plus = Plus;
  protected readonly Sliders = Sliders;

  protected badge(qty: number): string {
    if (qty <= 0) return 'bg-red-100 text-red-700';
    if (qty < 10) return 'bg-amber-100 text-amber-700';
    return 'bg-emerald-100 text-emerald-700';
  }
}

@if (loading() && items().length === 0) {
  <div class="py-16 text-center text-sm opacity-50">Loading…</div>
} @else if (items().length === 0) {
  <div class="py-16 text-center">
    <lucide-icon [img]="Boxes" class="mx-auto mb-3 h-10 w-10 opacity-30" />
    <p class="font-medium opacity-70">No inventory yet</p>
    <p class="mt-1 text-sm opacity-50">Items appear here once products are created.</p>
  </div>
} @else {
  <p-table [value]="items()" styleClass="w-full" [tableStyle]="{ 'min-width': '48rem' }">
    <ng-template pTemplate="header">
      <tr>
        <th pSortableColumn="productName">Product <p-sortIcon field="productName" /></th>
        <th pSortableColumn="sku">SKU <p-sortIcon field="sku" /></th>
        <th pSortableColumn="onHand" class="text-right">On hand <p-sortIcon field="onHand" /></th>
        <th pSortableColumn="reserved" class="text-right">
          Reserved <p-sortIcon field="reserved" />
        </th>
        <th pSortableColumn="available" class="text-right">
          Available <p-sortIcon field="available" />
        </th>
        @if (canManage()) {
          <th class="text-right">Actions</th>
        }
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-i>
      <tr>
        <td class="font-medium">{{ i.productName }}</td>
        <td>
          <span class="rounded bg-black/5 px-2 py-0.5 font-mono text-xs">{{ i.sku }}</span>
        </td>
        <td class="text-right">{{ i.onHand }}</td>
        <td class="text-right opacity-60">{{ i.reserved }}</td>
        <td class="text-right">
          <span
            class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold"
            [class]="badge(i.available)"
          >
            {{ i.available }} units
          </span>
        </td>
        @if (canManage()) {
          <td class="text-right">
            <button
              type="button"
              pTooltip="Receive stock"
              aria-label="Receive stock"
              class="rounded-lg p-2 opacity-70 hover:opacity-100"
              (click)="receive.emit(i)"
            >
              <lucide-icon [img]="Plus" class="h-4 w-4" />
            </button>
            <button
              type="button"
              pTooltip="Adjust stock"
              aria-label="Adjust stock"
              class="rounded-lg p-2 opacity-70 hover:opacity-100"
              (click)="adjust.emit(i)"
            >
              <lucide-icon [img]="Sliders" class="h-4 w-4" />
            </button>
          </td>
        }
      </tr>
    </ng-template>
  </p-table>

  @if (loading()) {
    <div
      class="border-t py-3 text-center text-xs opacity-50"
      style="border-color: var(--p-content-border-color)"
    >
      Refreshing…
    </div>
  }
}

// ui/src/features/inventory-management/components/InventoryTable.tsx
import { Boxes, Plus, Sliders } from 'lucide-react';
import { Tooltip } from '../../../components/Tooltip';
import type { InventoryItem } from '../types';

interface Props {
  items: InventoryItem[];
  loading: boolean;
  canManage: boolean;
  onReceive: (item: InventoryItem) => void;
  onAdjust: (item: InventoryItem) => void;
}

const stockBadgeCls = (qty: number) => {
  if (qty <= 0) return 'bg-red-100 text-red-700';
  if (qty < 10) return 'bg-amber-100 text-amber-700';
  return 'bg-emerald-100 text-emerald-700';
};

export const InventoryTable = ({ items, loading, canManage, onReceive, onAdjust }: Props) => {
  if (loading && items.length === 0) {
    return <div className="py-16 text-center text-slate-400 text-sm">Loading…</div>;
  }

  if (items.length === 0) {
    return (
      <div className="py-16 text-center">
        <Boxes className="w-10 h-10 text-slate-300 mx-auto mb-3" />
        <p className="text-slate-500 font-medium">No inventory yet</p>
        <p className="text-sm text-slate-400 mt-1">Items appear here once products are created.</p>
      </div>
    );
  }

  return (
    <>
      <table className="w-full text-sm">
        <thead>
          <tr className="bg-slate-50 border-b border-slate-200">
            <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Product</th>
            <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">SKU</th>
            <th className="text-right px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">On hand</th>
            <th className="text-right px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Reserved</th>
            <th className="text-right px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Available</th>
            {canManage && <th className="text-right px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Actions</th>}
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100">
          {items.map(i => (
            <tr key={i.productId} className="hover:bg-slate-50 transition-colors">
              <td className="px-4 py-3.5 font-medium text-slate-900">{i.productName}</td>
              <td className="px-4 py-3.5">
                <span className="font-mono text-xs bg-slate-100 text-slate-600 px-2 py-0.5 rounded">{i.sku}</span>
              </td>
              <td className="px-4 py-3.5 text-right text-slate-700">{i.onHand}</td>
              <td className="px-4 py-3.5 text-right text-slate-500">{i.reserved}</td>
              <td className="px-4 py-3.5 text-right">
                <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold ${stockBadgeCls(i.available)}`}>
                  {i.available} units
                </span>
              </td>
              {canManage && (
                <td className="px-4 py-3.5">
                  <div className="flex items-center justify-end gap-1">
                    <Tooltip label="Receive stock">
                      <button
                        onClick={() => onReceive(i)}
                        className="p-1.5 text-slate-400 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors cursor-pointer"
                      >
                        <Plus className="w-4 h-4" />
                      </button>
                    </Tooltip>
                    <Tooltip label="Adjust stock">
                      <button
                        onClick={() => onAdjust(i)}
                        className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer"
                      >
                        <Sliders className="w-4 h-4" />
                      </button>
                    </Tooltip>
                  </div>
                </td>
              )}
            </tr>
          ))}
        </tbody>
      </table>
      {loading && (
        <div className="border-t border-slate-100 py-3 text-center text-slate-400 text-xs">Refreshing…</div>
      )}
    </>
  );
};
