// ui/src/app/features/products/components/products-table/products-table.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { LucideAngularModule, Package, Pencil, Trash2 } from 'lucide-angular';
import { TableModule } from 'primeng/table';
import { TooltipModule } from 'primeng/tooltip';
import { Product } from '../../models/product.model';

/** Products list on a sortable PrimeNG p-table, with empty/loading states. */
@Component({
  selector: 'app-products-table',
  imports: [TableModule, TooltipModule, LucideAngularModule],
  templateUrl: './products-table.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductsTableComponent {
  readonly products = input.required<Product[]>();
  readonly loading = input(false);
  readonly canManage = input(false);
  readonly edit = output<Product>();
  readonly remove = output<Product>();

  protected readonly Package = Package;
  protected readonly Pencil = Pencil;
  protected readonly Trash2 = Trash2;
}

@if (loading() && products().length === 0) {
  <div class="py-16 text-center text-sm opacity-50">Loading…</div>
} @else if (products().length === 0) {
  <div class="py-16 text-center">
    <lucide-icon [img]="Package" class="mx-auto mb-3 h-10 w-10 opacity-30" />
    <p class="font-medium opacity-70">No products yet</p>
    <p class="mt-1 text-sm opacity-50">Click "Add Product" to create one.</p>
  </div>
} @else {
  <p-table [value]="products()" styleClass="w-full" [tableStyle]="{ 'min-width': '40rem' }">
    <ng-template pTemplate="header">
      <tr>
        <th pSortableColumn="name">Name <p-sortIcon field="name" /></th>
        <th pSortableColumn="sku">SKU <p-sortIcon field="sku" /></th>
        <th pSortableColumn="price">Price <p-sortIcon field="price" /></th>
        @if (canManage()) {
          <th class="text-right">Actions</th>
        }
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-p>
      <tr>
        <td class="font-medium">{{ p.name }}</td>
        <td>
          <span class="rounded bg-black/5 px-2 py-0.5 font-mono text-xs">{{ p.sku }}</span>
        </td>
        <td>
          {{ p.currency }} <span class="font-medium">{{ p.price.toFixed(2) }}</span>
        </td>
        @if (canManage()) {
          <td class="text-right">
            <button
              type="button"
              pTooltip="Edit product"
              aria-label="Edit product"
              class="rounded-lg p-2 opacity-70 hover:opacity-100"
              (click)="edit.emit(p)"
            >
              <lucide-icon [img]="Pencil" class="h-4 w-4" />
            </button>
            <button
              type="button"
              pTooltip="Delete product"
              aria-label="Delete product"
              class="rounded-lg p-2 opacity-70 hover:opacity-100"
              (click)="remove.emit(p)"
            >
              <lucide-icon [img]="Trash2" class="h-4 w-4" />
            </button>
          </td>
        }
      </tr>
    </ng-template>
  </p-table>

  @if (loading()) {
    <div
      class="border-t py-3 text-center text-xs opacity-50"
      style="border-color: var(--p-content-border-color)"
    >
      Refreshing…
    </div>
  }
}

// ui/src/features/product-management/components/ProductsTable.tsx
import { Pencil, Trash2, Package } from 'lucide-react';
import { Tooltip } from '../../../components/Tooltip';
import type { Product } from '../types';

interface Props {
  products: Product[];
  loading: boolean;
  canManage: boolean;
  onEdit: (product: Product) => void;
  onDelete: (product: Product) => void;
}

export const ProductsTable = ({ products, loading, canManage, onEdit, onDelete }: Props) => {
  if (loading && products.length === 0) {
    return <div className="py-16 text-center text-slate-400 text-sm">Loading…</div>;
  }

  if (products.length === 0) {
    return (
      <div className="py-16 text-center">
        <Package className="w-10 h-10 text-slate-300 mx-auto mb-3" />
        <p className="text-slate-500 font-medium">No products yet</p>
        <p className="text-sm text-slate-400 mt-1">Click "Add Product" to create one.</p>
      </div>
    );
  }

  return (
    <>
      <div>
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-slate-50 border-b border-slate-200">
              <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Name</th>
              <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">SKU</th>
              <th className="text-left px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Price</th>
              {canManage && <th className="text-right px-4 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Actions</th>}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {products.map(p => (
              <tr key={p.id} className="hover:bg-slate-50 transition-colors">
                <td className="px-4 py-3.5 font-medium text-slate-900">{p.name}</td>
                <td className="px-4 py-3.5">
                  <span className="font-mono text-xs bg-slate-100 text-slate-600 px-2 py-0.5 rounded">{p.sku}</span>
                </td>
                <td className="px-4 py-3.5 text-slate-700">
                  {p.currency} <span className="font-medium">{p.price.toFixed(2)}</span>
                </td>
                {canManage && (
                  <td className="px-4 py-3.5">
                    <div className="flex items-center justify-end gap-1">
                      <Tooltip label="Edit product">
                        <button
                          onClick={() => onEdit(p)}
                          className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-colors cursor-pointer"
                        >
                          <Pencil className="w-4 h-4" />
                        </button>
                      </Tooltip>
                      <Tooltip label="Delete product">
                        <button
                          onClick={() => onDelete(p)}
                          className="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors cursor-pointer"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </Tooltip>
                    </div>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {loading && (
        <div className="border-t border-slate-100 py-3 text-center text-slate-400 text-xs">Refreshing…</div>
      )}
    </>
  );
};
